package com.badran.store.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Password reset payload containing the reset token and replacement password.
 */
@Data
@Schema(description = "Password reset token and replacement password.")
public class ResetPasswordRequest {

    @NotBlank(message = "Token is required")
    @Size(max = 36, message = "Token must not exceed 36 characters")
    @Schema(description = "Password reset token generated by the forgot-password endpoint.", example = "550e8400-e29b-41d4-a716-446655440000")
    private String token;

    @NotBlank(message = "New password is required")
    @Size(min = 6, max = 255, message = "Password must be between 6 and 255 characters long")
    @Schema(description = "New password with at least six characters.", example = "newPassword123")
    private String newPassword;
}
