server:
  port: 8080

spring:
  application:
    name: badran-store-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/badran_store
    username: najwanbadran
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: dGhpcy1pcy1hLXNlY3VyZS1hbmQtc3Ryb25nLXNlY3JldC1rZXktZm9yLWJhZHJhbi1jYXItd2FzaC1zdXBwbGllcw==
  expiration: 86400000
